spring:
  application:
    name: learner-user-api
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #    password: 
    #    
    password: root
    url: jdbc:mysql://localhost:3306/product_managment?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource: 
    password: ali
    url: jdbc:mysql://104.154.158.66:3306/learnerCrownClothing?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://35.202.101.253:5761/eureka/
  instance: 
    prefer-ip-address: true
